version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'satistuffed'
    ports:
      - '53306:3306'
    volumes:
      - mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  migrate:
    build:
      context: .
      dockerfile: docker/migrate/Dockerfile
    depends_on:
      - 'db'
    command: ['wait-for-it', 'db:3306', '--', 'echo', 'migrate']
    volumes:
      - ./db/migrations:/migrate/migrations

volumes:
  mysql:
    driver: 'local'
