FROM golang:1.15-buster

RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.13.0/migrate.linux-amd64.tar.gz | tar xvz
RUN mv ./migrate.linux-amd64 /usr/bin/migrate
COPY ./wait-for-it.sh /usr/bin/wait-for-it

WORKDIR /go/src/github.com/gomachan46/satistuffed

#COPY go.mod .
#COPY go.sum .
#RUN go mod download
